---
title: "Creating tensors"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Creating tensors}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(rTorch)
```

## Creating a tensor

If you are in a hurry to test rTorch, here some examples:

### Example 1

```{r}
library(rTorch)

a <- torch$tensor(c(1, 2, 3, 4, 5))
a
```

Notice that this is a `float` tensor (see the comma `,`). By default, rTorch will choose a 32-bit `float` for you.

```{r}
class(a)
a$dtype
```

### Example 2

```{r}
b <- torch$tensor(seq(1,10))
b
```

These are all integers.

```{r}
class(b)
b$dtype
```

### Example 3

```{r}
c <- torch$arange(1, 10)
c
```

```{r}
torch$ones(c(2L, 3L))
```

### Example 4

```{r}
torch$rand(5L, 4L)
```

### Example 5

```{r}
torch$linspace(1L, 10L, steps = 100L)
```

### Example 6

```{r}
torch$eye(5L)
```

### Example 7

```{r}
arr <- array(seq(1, 60), dim = c(5, 4, 3))
torch$as_tensor(arr)
```

### Example 8

```{r}
mat <- matrix(seq(1, 20), nrow = 5)
torch$as_tensor(mat)
```

### Example 9

```{r}
m <- torch$Tensor(list(list(1, 2), 
                  list(3, 4),
                  list(5, 6)
                  )
             )
m
```

```{r}
(shp <- m$shape)
m$size()
dim(m)
length(m)

```

```{r}
# tensor shape components
shp[[1]]
shp[[2]]

```

### Example 10

```{r}
# a tensor representing a 28x20 pixels image in 3 channels
(img <- torch$rand(3L, 28L, 28L))
```

```{r all-image-channels, fig.width=4, fig.height=4}
# plot the image three channels
image((img[1L,,]$numpy()), main = "channel 1")
image((img[2L,,]$numpy()), main = "channel 2")
image((img[3L,,]$numpy()), main = "channel 3")
```
